// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArVVPlTp6VBsN9ntpI18MfKnkff402L4s',
    appId: '1:745929968359:web:b43d5ab1d310096b513042',
    messagingSenderId: '745929968359',
    projectId: 'chatapp-425c9',
    authDomain: 'chatapp-425c9.firebaseapp.com',
    storageBucket: 'chatapp-425c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkRzueUvIPSYoOuEHvQBoAWupQLqV23iI',
    appId: '1:745929968359:android:60b4dd27332ad308513042',
    messagingSenderId: '745929968359',
    projectId: 'chatapp-425c9',
    storageBucket: 'chatapp-425c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAaMEygr7jCtw1_VNRWbS8a0aG6RZWu28',
    appId: '1:745929968359:ios:a4f9e988c5051fa9513042',
    messagingSenderId: '745929968359',
    projectId: 'chatapp-425c9',
    storageBucket: 'chatapp-425c9.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAaMEygr7jCtw1_VNRWbS8a0aG6RZWu28',
    appId: '1:745929968359:ios:a4f9e988c5051fa9513042',
    messagingSenderId: '745929968359',
    projectId: 'chatapp-425c9',
    storageBucket: 'chatapp-425c9.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArVVPlTp6VBsN9ntpI18MfKnkff402L4s',
    appId: '1:745929968359:web:921f207f3663fc2f513042',
    messagingSenderId: '745929968359',
    projectId: 'chatapp-425c9',
    authDomain: 'chatapp-425c9.firebaseapp.com',
    storageBucket: 'chatapp-425c9.appspot.com',
  );
}
